name: Build FakePlayer 1.21.5

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: maven

      - name: Download missing dependencies
        run: |
          mkdir -p minecraft-fakeplayer/fakeplayer-core/lib
          curl -L -o minecraft-fakeplayer/fakeplayer-core/lib/OpenInv.jar https://jitpack.io/com/github/kaaiian/OpenInv/1.0/OpenInv-1.0.jar
          curl -L -o minecraft-fakeplayer/fakeplayer-core/lib/PlaceholderAPI-2.11.6.jar https://repo.placeholderapi.com/PlaceholderAPI/2.11.6/PlaceholderAPI-2.11.6.jar

      - name: Build FakePlayer 1.21.5
        run: mvn clean package -pl fakeplayer-v1_21_5 -am -DskipTests
        
