name: Build FakePlayer 1.21.5

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: maven

      - name: Build FakePlayer 1.21.5
        run: mvn clean package -pl fakeplayer-v1_21_5 -am -DskipTests
